### ISSUE TITLE
can't authenticate

### ISSUE THREAD

**Issue by wlwise** [arei/node-untappd#13]
Hey arei - when I try to run your example with my id/secret, I get the error below.  

  { code: 500,
     error_detail: 'Please pass via GET using the parameter \'client_secret\' and \'client_id\'',
     error_type: 'invalid_param',
     developer_friendly: '/v4/user/checkins/',
     response_time: { time: 0.003, measure: 'seconds' } },
  response: [] }

**Comment by Saffraxy** [comment]
Did you ever get an answer to this?
