### ISSUE TITLE
Stale example usage

### ISSUE THREAD

**Issue by machawk1** [arei/node-untappd#17]
Per the README:
> Below is a list of sites where you can see node-untappd in production use.
> * http://www.arei.net - arei's website which shows the last beer he drank in the upper right corner.

![Screen Shot 2019-05-22 at 12 33 15 PM](https://user-images.githubusercontent.com/2514780/58192047-e2dedc80-7c8d-11e9-8e73-358de3daaa92.png)

The linked site no longer has that information "in the upper right corner".

**Comment by arei** [comment]
Thanks for the ticket. Unfortunately, this entire library is pretty stale and not really in active development anymore.  Feel free to submit a PR to fix things though.
